name: Build

on:
  push:
    paths:
      - "apps/status-page/**"
      - "packages/ui/**"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build status page
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Build status page application
        run: |
          pnpm install
          pnpm run build --filter status-page

      - name: Build and push Docker image for status page
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./apps/status-page
          push: true
          tags: |
            naueramant/opsway-status-page:${{ steps.prep.outputs.BUILD_ID }}
